// components/BlogCards.tsx
import Link from "next/link";
import Image from "next/image";

interface Story {
  uuid: string;
  full_slug: string;
  name: string;
  content: {
    image?: { filename: string };
  };
}

export default function BlogCards({ stories }: { stories: Story[] }) {
  return (
    <div className="gap-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
      {stories.map((story) => (
        <Link
          key={story.uuid}
          href={`/${story.full_slug}`}
          title={story.name}
          className="group cursor-pointer flex-shrink-0 bg-black-500 border rounded-xl overflow-hidden shadow-xl"
        >
          {story.content.image?.filename && (
            <div className="rounded-t-xl overflow-hidden aspect-video relative">
              <Image
                src={story.content.image.filename}
                alt={story.name}
                fill
                className="object-cover object-center group-hover:scale-110 transition-transform duration-300"
              />
            </div>
          )}
          <div className="p-6">
            <div className="font-bold line-clamp-2 duration-300">{story.name}</div>
          </div>
        </Link>
      ))}
    </div>
  );
}

// app/components/BlogCards.vue
<script setup lang="ts">
interface Story {
    content: {
        id: string | number
        image: {
            filename: string
        }
    }
    full_slug: string
    name: string
}

const props = defineProps<{
    stories: Story[]
}>()
</script>
<template>
    <div class="gap-6 grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3">
        <NuxtLink v-for="{ content, full_slug, name } in stories" :to="`/${full_slug}`" :key="content.id" :title="name"
            class="group cursor-pointer flex-shrink-0 bg-black-500 border rounded-xl overflow-hidden shadow-xl">
            <div class="rounded-t-xl overflow-hidden">
                    <img :src="content.image.filename" :alt="name" 
                        class="w-full object-center object-cover border-0 group-hover:scale-125 duration-300" />
                    </div>
                <div class="p-6">
                    <div class="font-bold line-clamp-2 duration-300 ">
                        {{ name }}
                    </div>
                </div>
        </NuxtLink>
    </div>
</template>
