// app/contacte/page.tsx
"use client";

import { useState } from "react";
import { Phone, Envelope } from "@phosphor-icons/react";
import ListaOficiilor from "@/components/ListaOficiilor";
import CallToAction from "@/components/CallToAction";
import { useFacebookPixel } from "@/hooks/useFacebookPixel";
import { Check } from "@phosphor-icons/react";

const WEB3FORMS_KEY = "c8f3c3c1-46ab-46bf-a139-4c4bb6265d95";

interface FormData {
  nume: string;
  email: string;
  telefon: string;
  mesaj: string;
}

interface FormErrors {
  nume?: string;
  email?: string;
  telefon?: string;
  mesaj?: string;
  general?: string;
}

function validateEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

function validatePhone(phone: string) {
  return /^\d{9}$/.test(phone.replace(/\s/g, ""));
}

export default function ContactePage() {
  const { trackEvent } = useFacebookPixel();
  const [formData, setFormData] = useState<FormData>({
    nume: "",
    email: "",
    telefon: "",
    mesaj: "",
  });
  const [errors, setErrors] = useState<FormErrors>({});
  const [loading, setLoading] = useState(false);
  const [sent, setSent] = useState(false);

  const validate = (data: FormData): FormErrors => {
    const errs: FormErrors = {};
    if (!data.nume || data.nume.length < 3)
      errs.nume = "Numele trebuie să conțină cel puțin 3 caractere";
    if (data.email && !validateEmail(data.email))
      errs.email = "Email-ul este invalid";
    if (data.telefon && !validatePhone(data.telefon))
      errs.telefon = "Telefonul trebuie să conțină 9 cifre";
    if (!data.email && !data.telefon)
      errs.general = "Este necesar să introduceți email-ul sau telefonul";
    if (!data.mesaj) errs.mesaj = "Mesajul este obligatoriu";
    if (data.mesaj && data.mesaj.length < 10)
      errs.mesaj = "Mesajul trebuie să conțină cel puțin 10 caractere";
    return errs;
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const errs = validate(formData);
    if (Object.keys(errs).length > 0) {
      setErrors(errs);
      return;
    }
    setLoading(true);
    try {
      const res = await fetch("https://api.web3forms.com/submit", {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify({
          ...formData,
          access_key: WEB3FORMS_KEY,
          subject: `${formData.nume} a trimis un mesaj ...`,
          from_name: "Ideal Credit Website Contact Form",
        }),
      });
      const data = await res.json();
      if (data.success) {
        setSent(true);
        trackEvent("SubmitApplication");
        setFormData({ nume: "", email: "", telefon: "", mesaj: "" });
        setTimeout(() => setSent(false), 4000);
      }
    } catch {
      setErrors({ general: "A apărut o eroare. Încercați din nou." });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="container my-4 md:my-6 relative">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">
        {/* Contact info */}
        <div className="card text-xl space-y-8 text-center">
          <h1 className="card-title text-center">Contacte</h1>
          <div className="flex gap-2 items-center">
            <Phone className="w-6 h-6 shrink-0 text-brand-500" weight="light" />
            <a href="tel:+37378805060" onClick={() => trackEvent("Contact")}>
              <span className="opacity-50">(+373)</span> 78 80 50 60
            </a>
          </div>
          <div className="flex gap-2 items-center">
            <Phone className="w-6 h-6 shrink-0 text-brand-500" weight="light" />
            <a href="tel:+37379066566" onClick={() => trackEvent("Contact")}>
              <span className="opacity-50">(+373)</span> 790 66 5 66
            </a>
          </div>
          <div className="flex gap-2.5 items-center">
            <Envelope className="w-6 h-6 shrink-0 text-brand-500" weight="light" />
            <a href="mailto:info@idealcredit.md" onClick={() => trackEvent("Contact")}>
              info@idealcredit.md
            </a>
          </div>
        </div>

        {/* Contact form */}
        <div className="card relative overflow-hidden">
          <h2 className="card-title text-center">Scrie-ne direct</h2>
          {sent ? (
            <div className="grid place-content-center my-16 text-center">
              <Check className="text-brand-500 h-16 w-16 mx-auto" />
              <div className="text-2xl mt-4">
                Mulțumim pentru mesaj.
                <br />
                Vă contactăm în curând!
              </div>
            </div>
          ) : (
            <form onSubmit={handleSubmit} className="space-y-6 mt-4">
              <div>
                <label className="block text-sm mb-1">Nume</label>
                <input
                  type="text"
                  value={formData.nume}
                  onChange={(e) => setFormData((p) => ({ ...p, nume: e.target.value }))}
                  className="w-full rounded-md border bg-black-500 px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-brand-500"
                />
                {errors.nume && <p className="text-red-500 text-xs mt-1">{errors.nume}</p>}
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm mb-1">Email</label>
                  <input
                    type="email"
                    value={formData.email}
                    onChange={(e) => setFormData((p) => ({ ...p, email: e.target.value }))}
                    className="w-full rounded-md border bg-black-500 px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-brand-500"
                  />
                  {errors.email && <p className="text-red-500 text-xs mt-1">{errors.email}</p>}
                </div>
                <div>
                  <label className="block text-sm mb-1">Mobil</label>
                  <input
                    type="tel"
                    value={formData.telefon}
                    onChange={(e) => setFormData((p) => ({ ...p, telefon: e.target.value }))}
                    className="w-full rounded-md border bg-black-500 px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-brand-500"
                  />
                  {errors.telefon && <p className="text-red-500 text-xs mt-1">{errors.telefon}</p>}
                </div>
              </div>
              {errors.general && <p className="text-red-500 text-xs">{errors.general}</p>}
              <div>
                <label className="block text-sm mb-1">Mesaj</label>
                <textarea
                  rows={4}
                  value={formData.mesaj}
                  onChange={(e) => setFormData((p) => ({ ...p, mesaj: e.target.value }))}
                  className="w-full rounded-md border bg-black-500 px-3 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-brand-500 resize-none"
                />
                {errors.mesaj && <p className="text-red-500 text-xs mt-1">{errors.mesaj}</p>}
              </div>
              <div className="flex justify-end">
                <button
                  type="submit"
                  disabled={loading}
                  className="bg-green-600 hover:bg-green-500 disabled:opacity-60 text-white px-6 py-2 rounded-md text-sm font-medium transition-colors"
                >
                  {loading ? "Se trimite..." : "Trimite"}
                </button>
              </div>
            </form>
          )}
        </div>
      </div>

      {/* Office locations */}
      <div className="mt-4 md:mt-6">
        <div id="adresa-oficiilor" className="-translate-y-14" />
        <div className="card">
          <h2 className="card-title text-center">Adresa oficiilor</h2>
          <ListaOficiilor />
        </div>
      </div>

      <CallToAction className="py-10" />
    </div>
  );
}

// app/pages/contacte.vue
<script setup lang="ts">

    import type { FormError, FormSubmitEvent } from '@nuxt/ui'

    import { localBusinessChisinauSchema, localBusinessCauseniSchema } from '@/utils/schema'
    const { trackEvent } = useFacebookPixel()

    useHead({
        title: 'Contacte și Adresa Oficiilor | Ideal Credit',
        titleTemplate: '%pageTitle',
        meta: [
            { name: 'description', content: 'Contactează Ideal Credit - adrese, telefoane și programul oficiilor. Consultanță gratuită pentru credite business și de consum. Suntem aici să te ajutăm.' },
            { name: 'keywords', content: 'ideal credit, credit pentru afaceri, credite Moldova, credite Chișinău, credite nebancare' }
        ],
    })
    const web3FormAccessKey = 'c8f3c3c1-46ab-46bf-a139-4c4bb6265d95'
    const formData = ref({
        nume: '',
        email: '',
        telefon: '',
        mesaj: '',
        access_key: web3FormAccessKey,
        subject: '',
        from_name: 'Website Contact Form'
    })
    const formSend = ref(false)
    const loading = ref(false)

    const validate = (state: any): FormError[] => {
        const errors = []
        if (state.email && !validateEmail(state.email)) errors.push({ name: 'email', message: 'Email-ul este invalid' })
        if (!state.nume || state.nume.length < 3) errors.push({ name: 'nume', message: 'Numele trebuie să conțină cel puțin 3 caractere' })
        if (state.telefon && !validatePhone(state.telefon)) errors.push({ name: 'telefon', message: 'Telefonul mobil trebuie să conțină 9 cifre' })

        //email or phone is required
        if (!state.email || !state.telefon) errors.push({ name: 'email_phone', message: 'Este necesar să introduceți email-ul sau telefonul' })

        if (!state.mesaj) errors.push({ name: 'mesaj', message: 'Mesajul este obligatoriu' })
        if(state.mesaj.length < 10) errors.push({ name: 'mesaj', message: 'Mesajul trebuie să conțină cel puțin 10 caractere' })

        return errors

    }

    async function submitForm(event: FormSubmitEvent<typeof formData>) {
        loading.value = true
        try {
            
            formData.value.subject = formData.value.nume + ' a trimis un mesaj ...';

            let response = await fetch('https://api.web3forms.com/submit', {
                method: 'POST',
                headers: {
                    "Content-Type": "application/json",
                    Accept: "application/json"
                },
                body: JSON.stringify(formData.value)
            })

            let  data = await response.json()

            if (data.success) {
                formSend.value = true;
                formData.value = {
                    nume: '',
                    email: '',
                    telefon: '',
                    mesaj: '',
                    access_key: web3FormAccessKey,
                    subject: '',
                    from_name: 'Ideal Credit Website Contact Form'
                }

                trackEvent('SubmitApplication');

                setTimeout(() => {
                    formSend.value = false;
                }, 3000)
                
            }
        } catch (e) {
            console.error(e)
        } finally {
            loading.value = false
        }
    }

    useSchemaOrg([
        localBusinessChisinauSchema,
        localBusinessCauseniSchema
    ])

</script>
<template>
    <div class="container sm-constainer relative my-4 md:my-6">
        
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">
            <div class="card text-xl space-y-8 text-center">
                <h1 class="card-title text-center">Contacte</h1>   
                <div class="flex gap-2 items-center">
                    <UIcon name="i-ph-phone-light" class="w-6 h-6 shrink-0 text-brand-500"/>
                    <a href="tel:+37378805060" @click="trackEvent('Contact')"><span class="opacity-50">(+373)</span> 78 80 50 60</a>
                </div>
                <div class="flex gap-2 items-center">
                    <UIcon name="i-ph-phone-light" class="w-6 h-6 shrink-0 text-brand-500"/>
                    <a href="tel:+37379066566" @click="trackEvent('Contact')"><span class="opacity-50">(+373)</span> 790 66 5 66</a>
                </div>
                <div class="flex gap-2.5 items-center">
                    <UIcon name="i-ph-envelope-light" class="w-6 h-6 shrink-0 text-brand-500"/>
                    <a href="mailto:info@idealcredit.md" @click="trackEvent('Contact')">info@idealcredit.md</a>
                </div>
            </div>
             <div class="card relative overflow-hidden">
            <h2 class="card-title text-center">Scrie-ne direct</h2>
            <UiLoading v-if="loading" local/>
            <div v-if="formSend" class="grid place-content-center my-16 duration-700">
                <UIcon name="i-ph-check" class="text-brand-500 h-32 w-32 mx-auto" />
                <div class="text-2xl mt-4">Mulțumim pentru mesaj.<br>Vă contactăm în curând!</div>
            </div>
            <UForm v-else class="space-y-6 contact-form" @submit="submitForm" :state="formData" :validate="validate">
                <UFormField label="Nume" name="nume">
                    <UInput v-model="formData.nume" />
                </UFormField>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <UFormField label="Email" name="email">
                        <UInput v-model="formData.email" />
                    </UFormField>
                    <UFormField label="Mobil" name="telefon">
                        <UInput v-model="formData.telefon" name="telefon" />
                    </UFormField>
                </div>
                <UFormField name="email_phone">

                </UFormField>
                <UFormField label="Mesaj" name="mesaj">
                    <UTextarea v-model="formData.mesaj" />
                </UFormField>
                <div class="flex justify-end">
                    <UButton type="submit" color="success" :loading="loading" :disabled="loading || formSend">
                        Trimite
                    </UButton>
                </div>
            </UForm>
        </div>
        </div>
        <div class="mt-4 md:mt-6">
            <div id="adresa-oficiilor" class="-translate-y-14"></div>
            <div class="card">
                <h2 class="card-title text-center">Adresa oficiilor</h2>
                <ListaOficiilor/>
            </div>
        </div>
        <CallToAction class="py-10"/>
    </div>
</template>
