// components/PaymentMethods.tsx
import Link from "next/link";
import Section from "@/components/ds/Section";
import Card from "@/components/ds/Card";
import Accent from "@/components/ds/Accent";

type Method = { label: string; title: string; description: React.ReactNode };

const methods: Method[] = [
    {
        label: "Recomandat",
        title: "Online Banking",
        description: "Transfer bancar/de pe card pe contul IBAN al Ideal Credit.",
    },
    {
        label: "Oficiu",
        title: "În numerar",
        description: (
            <>
                În unul din{" "}
                <Link href="/contacte#adresa-oficiilor" className="underline underline-offset-[3px] hover:text-white">
                    oficiile companiei
                </Link>{" "}
                Ideal Credit.
            </>
        ),
    },
    {
        label: "Bancă",
        title: "VictoriaBank",
        description: "La orice filială a băncii VictoriaBank din țară.",
    },
    {
        label: "Poștă",
        title: "Oficiu poștal",
        description: "La orice oficiu poștal din Republica Moldova.",
    },
];

export default function PaymentMethods() {
    return (
        <Section
            title={
                <>
                    Metode de <Accent>achitare</Accent> a creditului
                </>
            }
        >
            <div className="grid gap-5" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))" }}>
                {methods.map((method) => (
                    <Card key={method.title} className="gap-3 p-7">
                        <p className="text-xs font-semibold uppercase tracking-widest text-dc-text-dim">{method.label}</p>
                        <h3 className="text-[19px] font-bold text-dc-text">{method.title}</h3>
                        <p className="text-sm text-dc-text-muted leading-relaxed">{method.description}</p>
                    </Card>
                ))}
            </div>
        </Section>
    );
}

// components/PaymentMethods.vue
<script setup>

const list = [
    {
        title: 'Ideal Credit',
        description: 'În unul din <a href="/contacte#adresa-oficiilor" class="underline">oficiile companiei</a>',
    },
    {
        title: 'Victoriabank',
        description: 'La orice filială a băncii Victoriabank',
    },
    {
        title: 'VB24 Web',
        description: 'Achitarea creditului online prin aplicația mobilă sau web a băncii Victoriabank',
    },
    {
        title: 'Online Banking',
        description: 'Transfer bancar sau de pe card pe contul IBAN al companiei Ideal Credit',
    },
     {
        title: 'Poșta Moldovei',
        description: 'Achitarea creditului la orice oficiu poștal din Republica Moldova',
    }
]
</script>
<template>
    <div class="space-y-6 card">
            <h2 class="card-title text-center">Metode de achitare a creditului</h2>
            <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
                <ul class="list-disc list-inside space-y-8 md:space-y-6">
                <li v-for="item in list" :key="item.title" class="flex gap-2 items-center">
                    <UIcon name="i-ph-dot-fill" class="w-5 h-5 text-brand-500/50 shrink-0" />
                    <div>
                        <span class="text-xl font-medium">{{ item.title }}:</span> <span class="text-white/80" v-html="item.description"></span>
                    </div>
                </li>
            </ul>
            <img src="/ideal-credit-metode-de-achitare.webp" alt="Metode de achitare" class="w-full sm:w-[70%] mx-auto -order-1 lg:order-2">
            </div>
        </div>
</template>
