// components/ui/ButtonsCTA.vue
<script setup>

const props = defineProps({
    toHeroSection: {
        type: Boolean,
        default: false
    }
})
const { trackEvent } = useFacebookPixel()
const phoneNumber = '+37378805060';
// const viberUrl = `viber://chat?number=${encodeURIComponent(phoneNumber)}`;

// let cls = 'flex flex-col justify-center items-center gap-3 px-4 rounded-lg aspect-square w-full hover:scale-105 transition-all duration-300'

const computedCls = computed(() => {
    return !props.toHeroSection ?  'lg:grid-cols-4' : ''
})

const clickContact = ref(false)

watch(clickContact, (val) => {
    if(val) {
        trackEvent('Contact');
    }
}, { once: true })

</script>
<template>
    <!-- <div v-if="toHeroSection" class="text-gray-300 text-center text-lg">Solicită un credit acum!</div> -->
    <div class="flex justify-center gap-6">
        <UButton icon="i-ph-pencil-simple-line" variant="outline" size="xl" to="/cerere-de-credit-online" title="Cerere de credit online" 
        class="ring-brand-500 text-brand-500 rounded-full px-4 hover:bg-brand-500/10 w-1/2 md:w-[180px] justify-center">
            <span>Cerere online</span>
        </UButton>
        <UButton icon="i-ph-whatsapp-logo-light" variant="outline" size="xl" to="https://wa.me/+37378805060" @click="clickContact = true" target="_blank" title="Scrieți-ne pe WhatsApp"
            class="ring-[#14ac4c] text-[#14ac4c] rounded-full px-4 w-1/2 md:w-[180px] justify-center">
            <span>WhatsApp</span>
        </UButton>
    </div>
</template>

// components/ui/ButtonsCTA.tsx
"use client";

import Link from "next/link";
import { MessageCircle, PencilLine } from "lucide-react";
import { useFacebookPixel } from "@/hooks/useFacebookPixel";

export default function ButtonsCTA() {
 const { trackEvent } = useFacebookPixel();

 return (
 <div className="flex flex-col sm:flex-row justify-center items-center gap-6 relative max-w-[320px] md:max-w-none mx-auto">
 <Link
 href="/cerere-de-credit-online"
 title="Cerere de credit online"
 className="flex items-center justify-center gap-2 w-full sm:w-[180px] h-10 px-4 rounded-full border border-brand-500 text-brand-500 hover:bg-brand-500/10 transition-colors duration-300 font-medium"
 >
 <PencilLine size={18} />
 <span className="truncate">Cerere online</span>
 </Link>
 <a
 href="https://wa.me/+37378805060"
 target="_blank"
 rel="noopener noreferrer"
 title="Scrieți-ne pe WhatsApp"
 onClick={() => trackEvent("Contact")}
 className="flex items-center justify-center gap-2 w-full sm:w-[180px] h-10 px-4 rounded-full border border-[#14ac4c] text-[#14ac4c] hover:bg-[#14ac4c]/10 transition-colors duration-300 font-medium"
 >
 <MessageCircle size={18} />
 <span className="truncate">WhatsApp</span>
 </a>
 </div>
 );
}
