// app/cookies/page.tsx
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Politica de Cookies - OCN Ideal Credit SRL",
    description: "Politica de Cookies - OCN Ideal Credit SRL",
};

export default function CookiesPage() {
    return (
        <div className="container sm-container my-6">
            <div className="card space-y-4 text-lg">
                <h1 className="card-title text-center">
                    Politica de Cookies
                    <br />
                    OCN Ideal Credit SRL
                </h1>

                <p>
                    Această Politică de Cookies explică modul în care OCN Ideal Credit SRL (&quot;noi&quot;, &quot;nouă&quot; sau
                    &quot;compania noastră&quot;) utilizează cookies și tehnologii similare pe site-ul nostru web.
                </p>

                <h2 className="text-xl mt-8 mb-2">Ce sunt cookie-urile?</h2>
                <p>
                    Cookie-urile sunt fișiere text mici care sunt plasate pe dispozitivul dvs. atunci când vizitați un site web. Acestea
                    sunt utilizate pe scară largă pentru a face site-urile web să funcționeze sau să funcționeze mai eficient, precum și
                    pentru a furniza informații proprietarilor site-ului.
                </p>

                <h2 className="text-xl mt-8 mb-2">Ce tipuri de cookies folosim?</h2>
                <p>Utilizăm următoarele tipuri de cookies:</p>
                <ul className="list-inside list-decimal space-y-2.5 mt-2">
                    <li>
                        <strong>Cookies strict necesare:</strong> Esențiale pentru funcționarea site-ului nostru web.
                    </li>
                    <li>
                        <strong>Cookies de performanță:</strong> Ne permit să numărăm vizitele și sursele de trafic.
                    </li>
                    <li>
                        <strong>Cookies funcționale:</strong> Permit site-ului să ofere funcționalități îmbunătățite.
                    </li>
                    <li>
                        <strong>Cookies de targetare:</strong> Pot fi setate de partenerii noștri de publicitate.
                    </li>
                </ul>

                <h2 className="text-xl mt-8 mb-2">Cookies de terță parte</h2>
                <p>Utilizăm servicii de la terțe părți care pot seta cookies:</p>
                <ul className="list-inside list-decimal space-y-2.5 mt-2">
                    <li>
                        <strong>Google Analytics:</strong> Analizăm modul în care vizitatorii folosesc site-ul nostru.
                    </li>
                    <li>
                        <strong>Meta (Facebook):</strong> Utilizăm pixeli Meta pentru a măsura eficacitatea reclamelor.
                    </li>
                    <li>
                        <strong>Meta Ads și Google Ads:</strong> Pot utiliza cookies pentru reclame relevante.
                    </li>
                    <li>
                        <strong>Cloudflare:</strong> Îmbunătățim performanța și securitatea site-ului nostru.
                    </li>
                </ul>

                <h2 className="text-xl mt-8 mb-2">Cum puteți controla cookies?</h2>
                <p>
                    Puteți controla și/sau șterge cookies după cum doriți. Puteți șterge toate cookies care sunt deja pe computerul dvs. și
                    puteți seta majoritatea browserelor să le blocheze.
                </p>

                <h2 className="text-xl mt-8 mb-2">Contact</h2>
                <div className="mt-2">
                    OCN Ideal Credit SRL,
                    <br />
                    or.Căușeni, str.Mihai Eminescu, nr.17, of.47
                    <br />
                    email: info@idealcredit.md
                    <br />
                    tel: 079066566, 078805060
                </div>

                <p className="mt-8 text-gray-500">Această Politică de Cookies a fost actualizată ultima dată la 26.09.2024.</p>
            </div>
        </div>
    );
}

// pages/cookies.vue
<script setup>
useHead({
    title: 'Politica de Cookies - OCN Ideal Credit SRL',
    titleTemplate: '%pageTitle',
    meta: [
        { name: 'description', content: 'Politica de Cookies - OCN Ideal Credit SRL' },
    ],
})
</script>

<template>
    <div class="container sm-container card light my-6">
        <h1 class="card-title text-center">Politica de Cookies<br>OCN Ideal Credit SRL</h1>

        <p>Această Politică de Cookies explică modul în care OCN Ideal Credit SRL ("noi", "nouă" sau "compania noastră") utilizează cookies și tehnologii similare pe site-ul nostru web. Vă rugăm să citiți cu atenție această politică pentru a înțelege cum colectăm și utilizăm informațiile.</p>

<h2 class="text-xl mt-8 mb-2">Ce sunt cookie-urile?</h2>

<p>Cookie-urile sunt fișiere text mici care sunt plasate pe dispozitivul dvs. atunci când vizitați un site web. Acestea sunt utilizate pe scară largă pentru a face site-urile web să funcționeze sau să funcționeze mai eficient, precum și pentru a furniza informații proprietarilor site-ului.</p>

<h2 class="text-xl mt-8 mb-2">Ce tipuri de cookies folosim?</h2>

<p>Utilizăm următoarele tipuri de cookies:</p>

<ul class="list-inside list-decimal space-y-2.5 mt-2">
    <li><strong>Cookies strict necesare:</strong> Aceste cookies sunt esențiale pentru funcționarea site-ului nostru web și nu pot fi dezactivate în sistemele noastre.</li>
    <li><strong>Cookies de performanță:</strong> Aceste cookies ne permit să numărăm vizitele și sursele de trafic, astfel încât să putem măsura și îmbunătăți performanța site-ului nostru.</li>
    <li><strong>Cookies funcționale:</strong> Aceste cookies permit site-ului să ofere funcționalități și personalizare îmbunătățite.</li>
    <li><strong>Cookies de targetare:</strong> Aceste cookies pot fi setate prin site-ul nostru de partenerii noștri de publicitate.</li>
</ul>

<h2 class="text-xl mt-8 mb-2">Cookies de terță parte</h2>

<p>Utilizăm servicii de la terțe părți care pot seta cookies pe dispozitivul dvs. Acestea includ:</p>

<ul class="list-inside list-decimal space-y-2.5 mt-2">
    <li><strong>Google Analytics:</strong> Utilizăm Google Analytics pentru a analiza modul în care vizitatorii folosesc site-ul nostru. Google Analytics setează cookies pentru a colecta informații și a raporta statistici de utilizare a site-ului, fără a identifica personal vizitatorii individuali.</li>
    <li><strong>Meta (Facebook):</strong> Utilizăm pixeli Meta pentru a măsura eficacitatea reclamelor noastre și pentru a înțelege acțiunile pe care le întreprindeți pe site-ul nostru.</li>
    <li><strong>Meta Ads și Google Ads:</strong> Aceste servicii pot utiliza cookies pentru a vă arăta reclame relevante pe alte site-uri web pe care le vizitați.</li>
    <li><strong>Cloudflare:</strong> Utilizăm Cloudflare pentru a îmbunătăți performanța și securitatea site-ului nostru. Cloudflare poate seta cookies pentru a identifica traficul de încredere.</li>
</ul>

<h2 class="text-xl mt-8 mb-2">Cum puteți controla cookies?</h2>

<p>Puteți controla și/sau șterge cookies după cum doriți. Puteți șterge toate cookies care sunt deja pe computerul dvs. și puteți seta majoritatea browserelor să le blocheze. Dacă faceți acest lucru, este posibil să trebuiască să ajustați manual unele preferințe de fiecare dată când vizitați un site, iar unele servicii și funcționalități s-ar putea să nu funcționeze.</p>

<h2 class="text-xl mt-8 mb-2">Modificări ale politicii de cookies</h2>

<p>Ne rezervăm dreptul de a modifica această politică de cookies în orice moment. Orice modificări vor fi postate pe această pagină.</p>

<h2 class="text-xl mt-8 mb-2">Contact</h2>

<p>Dacă aveți întrebări despre politica noastră de cookies, vă rugăm să ne contactați la:</p>

<div class="mt-2"> 
    OCN Ideal Credit SRL,<br>
    or.Căușeni, str.Mihai Eminescu, nr.17, of.47<br>
    email: info@idealcredit.md<br>
    tel: 079066566, 078805060<br>
</div>

<p class="mt-8">Această Politică de Cookies a fost actualizată ultima dată la 26.09.2024.</p>
    </div>
</template>
