// nuxt-project/app/pages/blog/[slug].vue
<script setup>
import { richTextResolver } from '@storyblok/richtext';
const route = useRoute();
const { render } = richTextResolver();

const story = await useStoryblok('blog/' + route.params.slug, { version: 'published' });

const htmlText = computed(() => {
    return render(story.value.content.content)
})

useHead({
    title: story?.value.name,
    titleTemplate: '%pageTitle',
    meta: [
        { name: 'keywords', content: 'credite rapide, împrumuturi, articole financiare, credite pentru afaceri' },
        { name: 'description', content: story?.value.content.meta_description },
        { name: 'robots', content: 'index, follow' },
        { property: 'og:locale', content: 'ro_RO' },
        { property: 'og:site_name', content: 'Ideal Credit' },
        { property: 'og:url', content: `https://idealcredit.md${route.fullPath}` },
        { property: 'og:type', content: `blogpost` },
        { property: 'og:image', content: story?.value.content.image.filename },
        { property: 'og:image:alt', content: story?.value.name },
        { property: 'og:title', content: story?.value.name },
        { property: 'og:description', content: story?.value.content.meta_description },
    ],
})

useSchemaOrg([
    defineArticle({
        // name and description can usually be inferred
        '@type': 'BlogPosting',
        headline: story?.value.name,
        description: story?.value.content.meta_description,
        image: story?.value.content.image.filename,
        datePublished: story?.value.created_at,
        dateModified: story?.value.published_at,
    })
])

</script>

<template>
    <div class="py-4 md:py-8 blog-page">
        <div class="container sm-container" v-if="story">
            <h1 class="text-2xl md:text-3xl mb-4 font-bold">{{ story?.name }}</h1>
            <div>
                <img :src="story.content?.image?.filename" :alt="story.content.image.alt | story.name"
                    class="w-full object-center object-cover border-0 rounded aspect-video" />
            </div>
            <div class="mt-6">
                <div class="richtext text-lg" v-html="htmlText">
                </div>
            </div>
            <div class="mt-6 space-y-2 border-t pt-6">
                <p>Vă mulțumim că ați citit articolul <span class="font-bold">"{{ story?.name }}"</span>.</p>
                <p>Vedeți și <nuxt-link to="/blog" title="Blog financiar" class="link">alte articole</nuxt-link> pentru mai multe informații.</p>
            </div>
        </div>
    </div>
</template>

// app/blog/[slug]/page.tsx
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { richTextResolver } from "@storyblok/richtext";
import { notFound } from "next/navigation";

const TOKEN = process.env.STORYBLOK_ACCESS_TOKEN;

async function getStory(slug: string) {
    try {
        const res = await fetch(`https://api.storyblok.com/v2/cdn/stories/blog/${slug}?token=${TOKEN}&version=published`, {
            next: { revalidate: 3600 },
        });
        if (!res.ok) return null;
        const data = await res.json();
        return data.story ?? null;
    } catch {
        return null;
    }
}

export async function generateStaticParams() {
    try {
        const res = await fetch(`https://api.storyblok.com/v2/cdn/stories?starts_with=blog&token=${TOKEN}&version=published&per_page=100`, {
            next: { revalidate: 3600 },
        });
        if (!res.ok) return [];
        const data = await res.json();
        return (data.stories ?? []).map((s: { slug: string }) => ({ slug: s.slug }));
    } catch {
        return [];
    }
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
    const { slug } = await params;
    const story = await getStory(slug);
    if (!story) return {};
    return {
        title: story.name,
        description: story.content?.meta_description,
        openGraph: {
            title: story.name,
            description: story.content?.meta_description,
            images: story.content?.image?.filename ? [story.content.image.filename] : [],
            type: "article",
        },
        alternates: { canonical: `https://idealcredit.md/blog/${slug}` },
    };
}

export default async function BlogPostPage({ params }: { params: Promise<{ slug: string }> }) {
    const { slug } = await params;
    const story = await getStory(slug);
    if (!story) notFound();

    const { render } = richTextResolver();
    const htmlText = story.content?.content ? String(render(story.content.content)) : "";

    return (
        <div className="py-4 md:py-8 blog-page">
            <div className="container sm-container">
                <h1 className="text-2xl md:text-3xl mb-4 font-bold">{story.name}</h1>
                {story.content?.image?.filename && (
                    <div className="relative w-full aspect-video rounded overflow-hidden">
                        <Image
                            src={story.content.image.filename}
                            alt={story.content.image.alt || story.name}
                            fill
                            className="object-cover object-center"
                            priority
                        />
                    </div>
                )}
                <div className="mt-6">
                    <div className="richtext text-lg" dangerouslySetInnerHTML={{ __html: htmlText }} />
                </div>
                <div className="mt-6 space-y-2 border-t pt-6">
                    <p>
                        Vă mulțumim că ați citit articolul <span className="font-bold">&quot;{story.name}&quot;</span>.
                    </p>
                    <p>
                        Vedeți și{" "}
                        <Link href="/blog" title="Blog financiar" className="link">
                            alte articole
                        </Link>{" "}
                        pentru mai multe informații.
                    </p>
                </div>
            </div>
        </div>
    );
}
