// app/pages/credite/credit-pentru-agricultura.vue
<script setup>
import ShortAboutUs from '~/components/ShortAboutUs.vue';
import { businessCreditSchema, creditConditionsSchema } from '@/utils/schema'

useHead({
    title: 'Credit pentru agricultură | Ideal Credit',
    titleTemplate: '%pageTitle',
    meta: [
        { name: 'description', content: 'Credit pentru agricultură - finanțare pentru tehnică, semințe, îngrășăminte, pesticide și lucrări agricole. Condiții simple și transparente!' },
        { name: 'keywords', content: 'credit pentru agricultură, business credit, credit rapid, credit Moldova, credit online, împrumuturi nebancare' }
    ],
})

useSchemaOrg([
    businessCreditSchema,
])

</script>
<template>
    <div class="relative pt-10 md:pt-12">
        <div class="bg-squares -mt-[1px]"></div>
        <div class="container">
            <UiRecenziiButton class="mb-16"/>
            <h1 class="font-semibold text-center text-5xl md:text-8xl">Credit pentru<br> agricultură</h1>
            <p class="text-center mt-6 px-4 md:px-0 text-gray-400 md:text-xl md:max-w-xl mx-auto text-lg font-light">Credit pentru agricultură - tehnică, semințe, îngrășăminte, pesticide și lucrări agricole. Proces simplu și transparent.</p>
            <UiMainCTA class="mt-16"/>
            <div class="cs-blur cs-blur--center z-[-1]"></div>
            <CalculatorCredit class="mt-18 md:mt-24"/>
        </div>
    </div>
    <section class="container">
        <h2 class="title text-center">Condițiile de creditare</h2>
        <ul class="w-full grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">
            <li v-for="item in creditConditionsSchema.pj.list" class="flex text-xl items-center gap-2 card">
                <UIcon name="i-ph-check" class="w-5 h-5 flex-shrink-0 text-green-400" />
                <span>{{ item }}</span>
            </li>
        </ul>
        <UiInfo class="mt-6">În funcție de evaluarea riscului de credit, se va solicita garanții adiționale: fidejusiune sau gaj imobil.</UiInfo>
    </section>
     <section class="container">
        <LazyHowItWorks />
    </section>
    <section>
        <div class="container text-lg space-y-4">
            <h2 class="card-title text-center">Credit pentru agricultură</h2>
            <p>Este un împrumut pentru fermieri și companii agricole (SRL, ÎI) care au nevoie de capital pentru cumpărarea tehnicii agricole, achiziția de semințe și fertilizanți sau plata lucrărilor sezoniere.</p>
            <h3 class="text-2xl pt-4">Scopuri principale</h3>
            <ul class="list-outside list-disc ml-6 text-gray-400">
                <li>Tehnică și utilaje: tractoare, combine, remorci, pluguri, sisteme irigații</li>
                <li>Inputuri: semințe, îngrășăminte, pesticide</li>
                <li>Lucrări agricole: arat, semănat, recoltare, lucrări sezonieră contractate</li>
                <li>Capital de lucru: plata salariilor, furnizorilor, carburant, reparații urgente</li>
                <li>Refinanțare: consolidarea creditelor vechi într-un contract cu costuri mai bune</li>
            </ul>
            <h3 class="text-2xl pt-4">Beneficii pentru agricultori</h3>
            <ul class="list-outside list-disc ml-6 text-gray-400">
                <li>Acces rapid la capital: până la 400.000 lei pentru nevoi reale</li>
                <li>Termeni flexibili: negociem suma, perioada și garanțiile pentru situația ta</li>
                <li>Viteză și transparență: decizie preliminară în 1-3 ore; eliberare a banilor în 2-4 zile. Fără comisioane ascunse</li>
                <li>Plată adaptată sezonului: posibilitate de grafic de rambursare potrivit perioadei de recoltare</li>
            </ul>
            <h3 class="text-2xl pt-4">Criterii esențiale de eligibilitate (orientativ)</h3>
            <ul class="list-outside list-disc ml-6 text-gray-400">
                <li>Formă juridică: SRL sau ÎI înregistrate în Republica Moldova</li>
                <li>Vechime în activitate: minim 6 luni</li>
                <li>Cont bancar activ pe numele firmei și extrase bancare pentru ultimele 3-6 luni</li>
                <li>Dovada activității agricole: facturi, contracte de vânzare, declarații fiscale, registru de producție</li>
                <li>Garanții: garanție personală sau bun imobil/echipament, în funcție de suma solicitată</li>
            </ul>
        </div>
    </section>
    <section>
        <ShortAboutUs/>
    </section>
</template>

// app/credite/credit-pentru-agricultura/page.tsx
import type { Metadata } from "next";
import CalculatorCredit from "@/components/CalculatorCredit";
import HowItWorks from "@/components/HowItWorks";
import ShortAboutUs from "@/components/ShortAboutUs";
import Info from "@/components/ui/Info";
import RecenziiButton from "@/components/ui/RecenziiButton";
import MainCTA from "@/components/ui/MainCTA";
import { Check } from "lucide-react";
import { personalLoanSchema, creditConditionsSchema, businessCreditSchema } from "@/lib/schema";

export const metadata: Metadata = {
    title: "Credit pentru agricultură | Ideal Credit",
    description:
        "Credit pentru agricultură - finanțare pentru tehnică, semințe, îngrășăminte, pesticide și lucrări agricole. Condiții simple și transparente!",
    alternates: { canonical: "https://idealcredit.md/credite/credit-pentru-agricultura" },
};

export default function CreditAgriculturaPage() {
    return (
        <>
            <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(businessCreditSchema) }} />
            <div className="relative pt-10 md:pt-12">
                <div className="bg-squares -mt-[1px]" />
                <div className="container">
                    <RecenziiButton className="mb-16" />
                    <h1
                        className="font-semibold text-center text-5xl md:text-8xl"
                        dangerouslySetInnerHTML={{ __html: "Credit pentru<br />agricultură" }}
                    />
                    <p className="text-center mt-6 px-4 md:px-0 text-gray-400 md:text-xl md:max-w-xl mx-auto text-lg font-light">
                        Credit pentru agricultură - tehnică, semințe, îngrășăminte, pesticide și lucrări agricole. Proces simplu și
                        transparent.
                    </p>
                    <MainCTA className="my-16" />
                    <div className="cs-blur cs-blur--center z-[-1]" />
                    <CalculatorCredit />
                </div>
            </div>
            <section className="container">
                <h2 className="title text-center">Condițiile de creditare</h2>
                <ul className="w-full grid grid-cols-1 md:grid-cols-2 gap-4 md:gap-6">
                    {creditConditionsSchema.pj.list.map((item) => (
                        <li key={item} className="flex text-xl items-center gap-2 card">
                            <Check className="w-5 h-5 flex-shrink-0 text-green-400" strokeWidth={3} />
                            <span>{item}</span>
                        </li>
                    ))}
                </ul>
                <Info className="mt-6">
                    În funcție de evaluarea riscului de credit, se va solicita garanții adiționale: fidejusiune sau gaj imobil.
                </Info>
            </section>
            <section className="container">
                <HowItWorks />
            </section>
            <section>
                <div className="container text-lg space-y-4">
                    <h2 className="card-title text-center">Ce este un credit pentru agricultură?</h2>
                    <p>
                        Este un împrumut pentru fermieri și companii agricole (SRL, ÎI) care au nevoie de capital pentru cumpărarea tehnicii
                        agricole sau achiziția de inputuri.
                    </p>
                    <h3 className="text-2xl pt-4">Scopuri principale</h3>
                    <ul className="list-outside list-disc ml-6 text-gray-400">
                        <li>Tehnică și utilaje: tractoare, combine, remorci, sisteme irigații</li>
                        <li>Inputuri: semințe, îngrășăminte, pesticide</li>
                        <li>Lucrări agricole: arat, semănat, recoltare</li>
                        <li>Capital de lucru: plata salariilor, furnizorilor</li>
                    </ul>
                    <h3 className="text-2xl pt-4">Beneficii pentru agricultori</h3>
                    <ul className="list-outside list-disc ml-6 text-gray-400">
                        <li>Acces rapid la capital</li>
                        <li>Termeni flexibili</li>
                        <li>Viteză și transparență: decizie în 1-3 ore</li>
                    </ul>
                </div>
            </section>
            <ShortAboutUs />
        </>
    );
}
