// components/includes/Footer.vue
<script setup>
    const oficii = [
        {
            title: 'Sediul',
            address: 'or. Căușeni, str. M.Eminescu',
            addressNumbers: 'nr. 17,  of. 47',
            mobile: ['+37379066566', '0790 66 5 66'],
        },
        {
            title: 'Sucursala Nr. 1',
            address: 'm. Chișinău, str. Miron Costin',
            addressNumbers: 'nr. 25,  of. 115',
            mobile: ['+37378805060', '078 80 50 60'],
        }
    ]

    const links = [
        // {
        //     title: 'Credite de consum',
        //     link: '/credite-de-consum',
        // },
        // {
        //     title: 'Credit auto',
        //     link: '/credit-auto',
        // },
        // {
        //     title: 'Credite imobiliare',
        //     link: '/credite-imobiliare',
        // },
        // {
        //     title: 'Credite pentru afaceri',
        //     link: '/credite-pentru-afaceri',
        // },
        // {
        //     title: 'Credite pentru refinanțare',
        //     link: '/refinantare-credite',
        // },
        {
            title: 'Blog financiar >>',
            link: '/blog',
        },
    ]
</script>
<template>
    <footer class="bg-brand-bg border-t border-brand-color border-opacity-10 relative">
        <div class="container grid grid-cols-1 md:grid-cols-3 gap-y-10 md:gap-x-6 py-8 px-2 md:px-0">
            <div>
                <div class="flex items-center gap-3">
                    <IconsLogo class="h-10 " />
                    <div class="text-xl">Ideal Credit</div>
                </div>
                <p class="mt-4">oferă credite rapide nebancare cu dobânzi mici și fără comisioane ascunse, pentru persoane fizice și juridice din Republica Moldova.</p>
                <ul class="mt-4">
                                <li class="mb-2" v-for="item in links" :key="item.link">
                            <NuxtLink :to="item.link" class="text-lg underline underline-offset-2   ">{{ item.title }}</NuxtLink>
                        </li>
                            </ul>
            </div>
            <div class="md:col-span-2">
                <div class="h-10 text-xl flex items-center font-medium">Adresa oficiilor</div>
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6 mt-4">
                    <div v-for="oficiu in oficii" :key="oficiu.address">
                        <div class="font-bold mb-2">
                            {{ oficiu.title }}
                        </div>
                        <div class="flex gap-4 mb-4 items-center">
                            <div class="p-2 rounded-full bg-brand-raisin-black">
                                <Icon name="ph:map-pin-light" class="w-6 h-6 flex-shrink-0 text-brand-color text-opacity-50" />
                            </div>
                            <div>{{ oficiu.address }}<br>{{ oficiu.addressNumbers }}</div>
                        </div>
                        <a :href="'tel:' + oficiu.mobile[0]" class="flex gap-4 items-center">
                            <div class="p-2 rounded-full bg-brand-raisin-black">
                                <Icon name="ph:phone-light"  class="w-6 h-6 flex-shrink-0 text-brand-color text-opacity-50" />
                            </div>
                            <div>{{ oficiu.mobile[1] }}</div>
                        </a>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="container mb-4 mt-10">
            <p class="mb-0">În Legea nr. 202/2013 privind contractele de credit pentru consumatori, au fost impuse limite cu privire la:</p>
                <ul class="list-outside list-disc ml-6">
                    <li>Rata maximală a dobânzii anuale specificate în contractul de credit să nu fie mai mare de 50%.</li>
                    <li>Toate celelalte plăți aferente (comisioane, taxe, penalități, dobânzi de întârziere și orice alt tip de plată), cu excepția dobânzii, să nu depășească 0,04% /zi din valoarea totală a creditului pentru termenul de utilizare efectivă a creditului.</li>
                    <li>Costului total al creditului (care include dobânzi, comisioane, taxe, penalități, dobânzi de întârziere și orice alt tip de plată) să nu fie mai mare decât valoarea debursată conform contractului (cu excepția contractelor ipotecare).</li>
                </ul>
        </div>
        <div class="container my-6">
                        <!-- <div class="h-10 text-xl flex items-center font-medium">Linkuri</div> -->
                        
                        <div class="border p-2 rounded border-brand-color opacity-70 text-center"> <NuxtLink to="/autoritatea-de-supraveghere" rel="nofollow" title="Autoritatea de Supraveghere" class="text-brand-color text-sm">Autoritatea de Supraveghere și metodele de reclamații</NuxtLink></div>
            </div>
        <div class="container mt-6">
            <div class="divider"></div>
            <div class="flex justify-center py-6 gap-1">
                &copy; {{ new Date().getFullYear() }} - Organizația de Creditare Nebancară <strong>"Ideal Credit"</strong> SRL
            </div>
        </div>
    </footer>
</template>

// components/includes/Footer.tsx
"use client";

import Link from "next/link";
import { Phone, MapPin } from "lucide-react";
import Logo from "@/components/icons/Logo";
import { useFacebookPixel } from "@/hooks/useFacebookPixel";
import { OFFICES, GLOSSARY_LINKS } from "@/lib/constants";
import { cn } from "@/lib/utils";

const productLinks = [
    { href: "/credite/credit-pentru-nevoi-personale", label: "Nevoi personale" },
    { href: "/credite/credit-pina-la-salariu", label: "Până la salariu" },
    { href: "/credite/credit-pentru-automobil", label: "Automobil" },
    { href: "/credite/credit-pentru-reparatie", label: "Reparație" },
    { href: "/credite/credit-pentru-afaceri-mici", label: "Afaceri mici" },
    { href: "/credite", label: "Toate creditele" },
];

const companyLinks = [
    { href: "/despre-noi", label: "Despre noi" },
    { href: "/contacte", label: "Contacte" },
    { href: "/blog", label: "Blog" },
    { href: "/cerere-de-credit-online", label: "Cerere online" },
];

const legalLinks = [
    { href: "/terms", label: "Termeni" },
    { href: "/cookies", label: "Cookies" },
    { href: "/privacy", label: "Confidențialitate" },
    { href: "/autoritatea-de-supraveghere", label: "Autoritatea de Supraveghere", className: "underline text-green-500" },
];

export default function Footer() {
    const { trackEvent } = useFacebookPixel();

    return (
        <footer className="relative border-t border-white/5 bg-black-700/40 pt-16 pb-10">
            {/* Top: 4-col brand + nav groups */}
            <div className="container grid grid-cols-2 md:grid-cols-4 lg:grid-cols-5 gap-10 pb-10 border-b border-white/5">
                {/* Brand column */}
                <div className="col-span-2 lg:col-span-2 space-y-5">
                    <Link href="/" className="flex items-center gap-3">
                        <Logo className="w-8" />
                        <div className="flex flex-col">
                            <span className="text-xl font-semibold leading-tight">Ideal Credit</span>
                            <span className="text-xs text-brand-500 font-medium tracking-wide">Credite pentru succes!</span>
                        </div>
                    </Link>
                    <p className="text-sm text-gray-500 max-w-xs leading-relaxed">Credite nebancare pentru afaceri și consum în Moldova.</p>
                    <div className="flex gap-4 items-center">
                        {[
                            {
                                href: "https://www.instagram.com/idealcredit.md/",
                                title: "Instagram",
                                path: "M128,80a48,48,0,1,0,48,48A48.05,48.05,0,0,0,128,80Zm0,80a32,32,0,1,1,32-32A32,32,0,0,1,128,160ZM176,24H80A56.06,56.06,0,0,0,24,80v96a56.06,56.06,0,0,0,56,56h96a56.06,56.06,0,0,0,56-56V80A56.06,56.06,0,0,0,176,24Zm40,152a40,40,0,0,1-40,40H80a40,40,0,0,1-40-40V80A40,40,0,0,1,80,40h96a40,40,0,0,1,40,40ZM192,76a12,12,0,1,1-12-12A12,12,0,0,1,192,76Z",
                            },
                            {
                                href: "https://www.facebook.com/idealcredit.md",
                                title: "Facebook",
                                path: "M128,24A104,104,0,1,0,232,128,104.11,104.11,0,0,0,128,24Zm8,191.63V152h24a8,8,0,0,0,0-16H136V112a16,16,0,0,1,16-16h16a8,8,0,0,0,0-16H152a32,32,0,0,0-32,32v24H96a8,8,0,0,0,0,16h24v63.63a88,88,0,1,1,16,0Z",
                            },
                            {
                                href: "https://www.linkedin.com/company/idealcredit/",
                                title: "LinkedIn",
                                path: "M216,24H40A16,16,0,0,0,24,40V216a16,16,0,0,0,16,16H216a16,16,0,0,0,16-16V40A16,16,0,0,0,216,24Zm0,192H40V40H216V216ZM96,112v64a8,8,0,0,1-16,0V112a8,8,0,0,1,16,0Zm88,28v36a8,8,0,0,1-16,0V140a20,20,0,0,0-40,0v36a8,8,0,0,1-16,0V112a8,8,0,0,1,15.79-1.78A36,36,0,0,1,184,140ZM100,84A12,12,0,1,1,88,72,12,12,0,0,1,100,84Z",
                            },
                        ].map((s) => (
                            <a
                                key={s.title}
                                href={s.href}
                                target="_blank"
                                rel="noopener noreferrer"
                                title={`Ideal Credit pe ${s.title}`}
                                className="text-white hover:text-brand-500 hover:border-brand-500/40 transition-colors"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" className="w-8 h-8" fill="currentColor" viewBox="0 0 256 256">
                                    <path d={s.path} />
                                </svg>
                            </a>
                        ))}
                    </div>
                </div>

                {/* Produse */}
                <div>
                    <p className="text-xs uppercase tracking-wider text-gray-500 mb-4">Produse</p>
                    <ul className="space-y-2.5">
                        {productLinks.map((l) => (
                            <li key={l.href}>
                                <Link href={l.href} className="text-sm text-gray-500 hover:text-brand-500 transition-colors">
                                    {l.label}
                                </Link>
                            </li>
                        ))}
                    </ul>
                </div>

                {/* Companie */}
                <div>
                    <p className="text-xs uppercase tracking-wider text-gray-500 mb-4">Companie</p>
                    <ul className="space-y-2.5">
                        {companyLinks.map((l) => (
                            <li key={l.href}>
                                <Link href={l.href} className="text-sm text-gray-500 hover:text-brand-500 transition-colors">
                                    {l.label}
                                </Link>
                            </li>
                        ))}
                    </ul>
                </div>

                {/* Legal */}
                <div>
                    <p className="text-xs uppercase tracking-wider text-gray-500 mb-4">Legal</p>
                    <ul className="space-y-2.5">
                        {legalLinks.map((l) => (
                            <li key={l.href}>
                                <Link
                                    href={l.href}
                                    rel={l.href === "/autoritatea-de-supraveghere" ? "nofollow" : undefined}
                                    className={cn("text-sm text-gray-500 hover:text-brand-500 transition-colors", l?.className)}
                                >
                                    {l.label}
                                </Link>
                            </li>
                        ))}
                    </ul>
                </div>
            </div>

            {/* Offices row */}
            <div className="container py-10 grid grid-cols-1 md:grid-cols-2 gap-6">
                {OFFICES.map((oficiu) => (
                    <div key={oficiu.id} className="rounded-xl border border-white/5 bg-black-600/60 p-5">
                        <div className="flex items-center gap-2 font-medium text-white">
                            <MapPin size={18} className="text-green-500" />
                            {oficiu.title}
                        </div>
                        <p className="text-gray-500 mt-2 leading-relaxed">
                            {oficiu.city}, {oficiu.street},<br />
                            {oficiu.addressNumbers}
                        </p>
                        <p className="text-sm text-gray-500 mt-2">Luni - Vineri · 08:30 - 16:30</p>
                        <a
                            href={`tel:${oficiu.mobile}`}
                            onClick={() => trackEvent("Contact")}
                            className="mt-4 inline-flex items-center gap-2 h-10 px-4 rounded-full border border-brand-500/10 bg-brand-500/5 text-brand-500 hover:text-brand-500 hover:border-brand-500/40 transition-colors text-base font-medium"
                        >
                            <Phone size={14} />
                            {oficiu.mobileDisplay}
                        </a>
                    </div>
                ))}
            </div>

            {/* Legal excerpt */}
            <div className="container mt-12">
                <p className="mb-6 text-xl text-center">Extras din lege</p>
                <p className="mb-4 pl-6">
                    În Legea nr. 202/2013 privind contractele de credit pentru consumatori, au fost impuse limite cu privire la:
                </p>
                <ul className="list-outside list-disc ml-6 space-y-1.5 text-gray-500">
                    <li>Rata maximală a dobânzii anuale specificate în contractul de credit să nu fie mai mare de 50%.</li>
                    <li>
                        Toate celelalte plăți aferente (comisioane, taxe, penalități, dobânzi de întârziere și orice alt tip de plată), cu
                        excepția dobânzii, să nu depășească 0,04% /zi din valoarea totală a creditului pentru termenul de utilizare efectivă
                        a creditului.
                    </li>
                    <li>
                        Costul total al creditului (care include dobânzi, comisioane, taxe, penalități, dobânzi de întârziere și orice alt
                        tip de plată) să nu fie mai mare decât valoarea debursată conform contractului (cu excepția contractelor ipotecare).
                    </li>
                </ul>
            </div>

            {/* Glossary */}
            <div className="container mt-12">
                <p className="mb-6 text-xl text-center">Dicționar financiar</p>
                <ul className="list-outside list-disc ml-6 space-y-2.5 text-gray-500">
                    {GLOSSARY_LINKS.map((item) => (
                        <li key={item.name}>
                            <span className="font-bold">{item.name} - </span>
                            {item.desc}
                        </li>
                    ))}
                </ul>
            </div>

            {/* Copyright */}
            <div className="container mt-10 pt-8 border-t border-white/5 flex flex-col md:flex-row items-center justify-between gap-3 text-xs text-gray-500">
                <span>
                    &copy; {new Date().getFullYear()} Organizația de Creditare Nebancară{" "}
                    <strong className="text-gray-500">Ideal Credit</strong> SRL
                </span>
                <span>Toate drepturile rezervate.</span>
            </div>
        </footer>
    );
}
